name: dalfapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0  
  badges: ^3.1.2  
  provider: ^6.0.3
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.0 
  shimmer: ^2.0.0 
  http: ^0.13.3   
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.1.3
  google_fonts: ^4.0.4
  page_transition: ^2.0.9
  crypto: ^3.0.3
  # Ensure this is properly indented under dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: 
    - images/Dalf_carne/
